### ISSUE TITLE
Design API for converting data to/from bytes

### ISSUE THREAD

**Issue by dtolnay** [Robbepop/modular-bitfield#8]
The current #[bitfield] API is self-contained in the sense that within a single Rust application we can place data into bitfields and get the data back out, which is potentially useful for optimizing memory usage of memory-intensive applications but not the primary use of bitfields. For interacting with other systems, we would need more than this. For example to use modular-bitfield to manipulate incoming data packets from the outside world -- this isn't a thing that can be implemented using `new` and `get_*` and `set_*`. Would transmute be the recommended way for downstream code to solve this or is there a better approach?

**Comment by Robbepop** [comment]
Thanks for the suggestion!

The `to_bytes` conversion is simple. We can just generate:
```
fn to_bytes(&self) -> &[u8] { &self.data }
```

The `from_bytes` conversion is actually the annoying one since we may have to consider bitfield structs that might contain invalid bit sets. For example this could be well introduced with the feature to support non-powers-of-two enum bit specifiers.

Also it is an open question whether to take `[u8; N]` where N is the total number of bytes in the struct or whether something more generically useful such as `&[u8]` or `impl Iterator<Item = u8>` should be taken as argument in the `from_bytes` constructor.

Also for the cases with invalid bit ranges mentioned above we need to return a `Result` instead of `Self` directly.

**Comment by Robbepop** [comment]
With https://github.com/Robbepop/modular-bitfield/commit/48bd16c09226512653f5b27c159777084c43b3d1 in place we should have an easier life implementing a sane API for converting from bits.

**Comment by Robbepop** [comment]
Simplified implementation that does not yet respect the eventually future addition of non-power-of-two enums: https://github.com/Robbepop/modular-bitfield/commit/5c557985ead499083582cc6c7891377c6516a2bc
